[build-system]
    requires = ["setuptools>=64", "setuptools-scm"]
    build-backend = "setuptools.build_meta"

[project]
    name = "idftool"
    description = "Utility for flashing, provisioning, and interacting with Espressif SOCs running ESP-IDF"
    readme = "README.md"
    license = "Apache-2.0"
    requires-python = ">=3.10"
    dynamic = ["version"]
    dependencies = [
        "click>=8.1",
        "rich-click>=1.8",
        "esptool~=5.2.0",
        "esp-idf-defs~=0.1.3",
        "esp-idf-nvs-partition-gen~=0.2.0",
    ]

[project.scripts]
    idftool = "idftool.__main__:_main"

[project.urls]
    Source = "https://github.com/nebkat/idftool"

[tool.setuptools]
    packages = ["idftool"]

[tool.setuptools_scm]
